### ISSUE TITLE
Your Specs

### ISSUE THREAD

**Issue by nguyentu98lt** [dqbd/Acer-Spin-5-OpenCore#1]
I want to know ur spec,thks u

**Comment by dqbd** [comment]
Sure thing

- Model: Acer Spin 5 SP513-52N-577C
    - [https://snlookup.com/acer-spin-sp513-52n-notebook-nx-gr7ec-001-p137236](https://snlookup.com/acer-spin-sp513-52n-notebook-nx-gr7ec-001-p137236)
- CPU: i5-8250U Kaby Lake R
    - Base Frequency: 1.6 GHz
    - Core Boost: 3.4 GHz
- RAM: 8 GB DDR4
    - RAM frequency: 2 400 MHz
- GPU: Intel UHD 620
    - GRAM: 4 GB
- Disks: Micron M.2 256 GB 1100 MTFDDAV256TBN
- Audio Codec: Realtek High Definition Audio (SST) 6.0.8703.1
- WiFi: Qualcomm Atheros QCA61x4A
    - Model: QCNFA344A
    - USB dongle: RTL 8188EU
- Bluetooth: NFA344A Liteon
- Input Devices:
    - Touchpad: ELAN I2C Filter driver
    - Touch screen:
    - Biometric: ELAN WBF Fingerprint driver
- Display
    - 1920 x 1080 px
    - 13.3" device
